### ISSUE TITLE
关于计算值,每次都不一样的问题

### ISSUE THREAD

**Issue by satng** [satng/unidbg_douyin10#1]
用frida验证，相同的数据每次调用结果都不一样。

可能是cms内部有随机值，通过观察发现有一个类似function调用计数的值。 

其实我也比较感兴趣这个问题，后台是怎么验证这个值是正确的~

**Comment by stuhk** [comment]
怎么找到function调用计数的位置的？

**Comment by maiyao1988** [comment]
貌似不一定是计数，实测同一参数，不同启动调用的结果也不一样，一段时间内结果相同，但是相同多久的时间不固定
