### ISSUE TITLE
请问怎么把这个打包成能用的 jar包？

### ISSUE THREAD

**Issue by myvcgit** [satng/unidbg_douyin10#4]
我照着别人的参考用 
【Artifacts】 -> 【JAR】 -> 【From modules with dependences】
Main Class 为com.sun.jna.JniDispatchTest32
JAR files from libraries选extract to the target JAR
打包后运行出错，
Error: Could not find or load main class H:\Git\unidbg_douyin10\classes\artifacts\unidbg_jar\unidbg.jar
Caused by: java.lang.ClassNotFoundException: H:\Git\unidbg_douyin10\classes\artifacts\unidbg_jar\unidbg.jar
请问要怎么做？

**Comment by satng** [comment]
正常的IDEA打包流程，即可。
https://github.com/satng/unidbg_douyin10/releases/download/1/unidbg_jar.zip

如果集成到其它项目里去，需要做一个代码优化或文件目录的调整

**Comment by playniuniu** [comment]
大佬，我这边也是编译 Jar 包出错，求助一下

我的设置如下

![Tuzycwp9xYiWOGr](https://i.loli.net/2020/04/12/Tuzycwp9xYiWOGr.png)

然后运行

![XLwWneErB2t1KOR](https://i.loli.net/2020/04/12/XLwWneErB2t1KOR.png)

最后提示找不到类

![wtXUhYZbRHfniVq](https://i.loli.net/2020/04/12/wtXUhYZbRHfniVq.png)

请教一下到底应该怎样设置，才能成功打成 Jar 包呢？
